const clothesProducts = [
  {
    id: 1,
    name: 'Denim Jacket',
    price: 49.99,
    image: 'https://m.media-amazon.com/images/I/71raL1w6FML._AC_UL480_FMwebp_QL65_.jpg',
    category: 'Jackets',
    description: 'Classic denim jacket with a comfortable fit.',
  },
  {
    id: 2,
    name: 'Graphic T-Shirt',
    price: 19.99,
    image: 'https://m.media-amazon.com/images/I/511ZNJLtYvL._AC_UL480_FMwebp_QL65_.jpg',
    category: 'T-Shirts',
    description: 'Soft cotton t-shirt with a stylish graphic print.',
  },
  {
    id: 3,
    name: 'Slim Fit Jeans',
    price: 39.99,
    image: 'https://m.media-amazon.com/images/I/51GmUO78FvL._AC_UL480_FMwebp_QL65_.jpg',
    category: 'Jeans',
    description: 'Stylish slim-fit jeans with a modern look.',
  },
  {
    id: 4,
    name: 'Floral Dress',
    price: 59.99,
    image: 'https://m.media-amazon.com/images/I/51LvYLaI-5L._AC_UL480_FMwebp_QL65_.jpg',
    category: 'Dresses',
    description: 'Elegant floral dress, perfect for summer outings.',
  },
  {
    id: 5,
    name: 'Chinos Pants',
    price: 34.99,
    image: 'https://m.media-amazon.com/images/I/71f7A-nMvlL._AC_UL480_FMwebp_QL65_.jpg',
    category: 'Pants',
    description: 'Casual chinos pants with a relaxed fit.',
  },
  {
    id: 6,
    name: 'Leather Jacket',
    price: 99.99,
    image: 'https://m.media-amazon.com/images/I/61k4d-9W7RL._AC_UL480_FMwebp_QL65_.jpg',
    category: 'Jackets',
    description: 'Premium leather jacket for a bold, stylish look.',
  },
  {
    id: 7,
    name: 'Striped Polo Shirt',
    price: 24.99,
    image: 'https://m.media-amazon.com/images/I/61hDkTYnCdL._AC_UL480_FMwebp_QL65_.jpg',
    category: 'Shirts',
    description: 'Casual striped polo shirt made of breathable fabric.',
  },
  {
    id: 8,
    name: 'Sweatpants',
    price: 29.99,
    image: 'https://m.media-amazon.com/images/I/71Jukhvw8DL._AC_UL480_FMwebp_QL65_.jpg',
    category: 'Pants',
    description: 'Comfortable sweatpants, ideal for lounging or workouts.',
  },
  {
    id: 9,
    name: 'Hooded Sweatshirt',
    price: 39.99,
    image: 'https://m.media-amazon.com/images/I/71Qh7VTKgAL._AC_UL480_FMwebp_QL65_.jpg',
    category: 'Sweatshirts',
    description: 'Cozy hooded sweatshirt for everyday comfort.',
  },
  {
    id: 10,
    name: 'Maxi Skirt',
    price: 44.99,
    image: 'https://m.media-amazon.com/images/I/61+OnW2GPGL._AC_UL480_FMwebp_QL65_.jpg',
    category: 'Skirts',
    description: 'Flowing maxi skirt, perfect for a chic, casual look.',
  }
];

export default clothesProducts;
